import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AOSInit from "@/components/AOSInIt";


export const metadata: Metadata = {
  title: "Thief Dentist",
  description: "Generated by create next app",
  icons: {
    icon:'/dent-thief.svg',
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <AOSInit/>
        <Navbar />
        <main className="min-h-screen p-4">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
